// This file is autogenerated by liwe3-svelte
/* eslint-disable @typescript-eslint/no-explicit-any */

/*=== f2c_start __file ===*/

/*=== f2c_end __file ===*/

/** Tag */
export interface Tag {
	/** the main id field */
	id: string;
	/** The domain name */
	domain?: string;
	/** The tag name */
	name: string;
	/** The unique key tag <-> domain */
	name_domain: string;
	/** Number of times this tag has been used */
	count?: number;
	/** If the tag is visible to the public */
	visible?: boolean;
	/** The module using this tag. This is optional, default is 'system' (everywhere) */
	modules?: string[];
}

/** TagBind */
export interface TagBind {
	/** Record id */
	id: string;
	/** Domain */
	domain: string;
	/**  */
	id_tag?: string;
	/**  */
	id_obj?: string;
	/**  */
	module?: string;
}

/** TagSearchResult */
export interface TagSearchResult {
	/** The tag name */
	tag: string[];
	/** The id_obj */
	id_obj: string;
	/** The module */
	module: string;
}

/** TagBase */
export interface TagBase {
	/** The tag name */
	name?: string;
}

